services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: CHANNELS
        value: rylloc
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "!modgpt"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "Neogip"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:gmgh4uetmq3btlgudnpb5pzhs6wq34"
      - key: SEND_USERNAME
        value: "true"
