services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: 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
      - key: CHANNELS
        value: rylloc
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "!neog"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "Neogip"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:1vk5hgvavo2f1qo6ce6jwwhc2zxomi"
      - key: SEND_USERNAME
        value: "true"
